//
//  Copyright © 2019 MBition GmbH. All rights reserved.
//

import RealmSwift

@objcMembers class DBVehicleStatusModel: Object {
	
	// MARK: Properties
	dynamic var acChargingCurrentLimitation: DBVehicleStatusIntModel?
	dynamic var auxheatActive: DBVehicleStatusBoolModel?
	dynamic var auxheatRuntime: DBVehicleStatusIntModel?
	dynamic var auxheatState: DBVehicleStatusIntModel?
	dynamic var auxheatTime1: DBVehicleStatusIntModel?
	dynamic var auxheatTime2: DBVehicleStatusIntModel?
	dynamic var auxheatTime3: DBVehicleStatusIntModel?
	dynamic var auxheatTimeSelection: DBVehicleStatusIntModel?
	dynamic var auxheatWarnings: DBVehicleStatusIntModel?
	dynamic var averageSpeedReset: DBVehicleStatusDoubleModel?
	dynamic var averageSpeedStart: DBVehicleStatusDoubleModel?
	dynamic var bidirectionalChargingActive: DBVehicleStatusBoolModel?
	dynamic var chargeCouplerACLockStatus: DBVehicleStatusIntModel?
	dynamic var chargeCouplerACStatus: DBVehicleStatusIntModel?
	dynamic var chargeCouplerDCLockStatus: DBVehicleStatusIntModel?
	dynamic var chargeCouplerDCStatus: DBVehicleStatusIntModel?
	dynamic var chargeFlapACStatus: DBVehicleStatusIntModel?
	dynamic var chargeFlapDCStatus: DBVehicleStatusIntModel?
    dynamic var chargePrograms: DBVehicleStatusChargeProgramModel?
	dynamic var chargingActive: DBVehicleStatusBoolModel?
	dynamic var chargingBreakClockTimer: DBVehicleStatusChargingBreakClockTimerModel?
	dynamic var chargingError: DBVehicleStatusIntModel?
	dynamic var chargingErrorInfrastructure: DBVehicleStatusIntModel?
	dynamic var chargingErrorWim: DBVehicleStatusIntModel?
	dynamic var chargingMode: DBVehicleStatusIntModel?
	dynamic var chargingPower: DBVehicleStatusDoubleModel?
	dynamic var chargingPowerControl: DBVehicleStatusChargingPowerControlModel?
	dynamic var chargingPowerEcoLimit: DBVehicleStatusIntModel?
	dynamic var chargingStatus: DBVehicleStatusIntModel?
	dynamic var chargingTimeType: DBVehicleStatusBoolModel?
	dynamic var decklidLockState: DBVehicleStatusBoolModel?
	dynamic var decklidStatus: DBVehicleStatusBoolModel?
	dynamic var departureTime: DBVehicleStatusIntModel?
	dynamic var departureTimeIcon: DBVehicleStatusIntModel?
	dynamic var departureTimeMode: DBVehicleStatusIntModel?
	dynamic var departureTimeSoc: DBVehicleStatusIntModel?
	dynamic var departureTimeWeekday: DBVehicleStatusIntModel?
	dynamic var distanceElectricalReset: DBVehicleStatusDoubleModel?
	dynamic var distanceElectricalStart: DBVehicleStatusDoubleModel?
	dynamic var distanceGasReset: DBVehicleStatusDoubleModel?
	dynamic var distanceGasStart: DBVehicleStatusDoubleModel?
	dynamic var distanceReset: DBVehicleStatusDoubleModel?
	dynamic var distanceStart: DBVehicleStatusDoubleModel?
	dynamic var distanceZEReset: DBVehicleStatusIntModel?
	dynamic var distanceZEStart: DBVehicleStatusIntModel?
	dynamic var doorFrontLeftLockState: DBVehicleStatusBoolModel?
	dynamic var doorFrontLeftState: DBVehicleStatusBoolModel?
	dynamic var doorFrontRightLockState: DBVehicleStatusBoolModel?
	dynamic var doorFrontRightState: DBVehicleStatusBoolModel?
	dynamic var doorLockStatusGas: DBVehicleStatusBoolModel?
	dynamic var doorLockStatusOverall: DBVehicleStatusIntModel?
	dynamic var doorRearLeftLockState: DBVehicleStatusBoolModel?
	dynamic var doorRearLeftState: DBVehicleStatusBoolModel?
	dynamic var doorRearRightLockState: DBVehicleStatusBoolModel?
	dynamic var doorRearRightState: DBVehicleStatusBoolModel?
	dynamic var doorStatusOverall: DBVehicleStatusIntModel?
	dynamic var drivenTimeReset: DBVehicleStatusIntModel?
	dynamic var drivenTimeStart: DBVehicleStatusIntModel?
	dynamic var drivenTimeZEReset: DBVehicleStatusIntModel?
	dynamic var drivenTimeZEStart: DBVehicleStatusIntModel?
	dynamic var ecoScoreAccel: DBVehicleStatusIntModel?
	dynamic var ecoScoreBonusRange: DBVehicleStatusDoubleModel?
	dynamic var ecoScoreConst: DBVehicleStatusIntModel?
	dynamic var ecoScoreFreeWhl: DBVehicleStatusIntModel?
	dynamic var ecoScoreTotal: DBVehicleStatusIntModel?
	dynamic var electricConsumptionReset: DBVehicleStatusDoubleModel?
	dynamic var electricConsumptionStart: DBVehicleStatusDoubleModel?
	dynamic var electricalRangeSkipIndication: DBVehicleStatusBoolModel?
	dynamic var endOfChargeTime: DBVehicleStatusIntModel?
	dynamic var endOfChargeTimeRelative: DBVehicleStatusDoubleModel?
	dynamic var endOfChargeTimeWeekday: DBVehicleStatusIntModel?
	dynamic var engineHoodStatus: DBVehicleStatusBoolModel?
	dynamic var engineState: DBVehicleStatusBoolModel?
	let eventTimestamp = RealmOptional<Int64>()
	dynamic var evRangeAssistDriveOnSoc: DBVehicleStatusIntModel?
	dynamic var evRangeAssistDriveOnTime: DBVehicleStatusIntModel?
	dynamic var filterParticleLoading: DBVehicleStatusIntModel?
	dynamic var finOrVin: String = ""
	dynamic var flipWindowStatus: DBVehicleStatusBoolModel?
	dynamic var gasConsumptionReset: DBVehicleStatusDoubleModel?
	dynamic var gasConsumptionStart: DBVehicleStatusDoubleModel?
	dynamic var hybridWarnings: DBVehicleStatusIntModel?
	dynamic var ignitionState: DBVehicleStatusIntModel?
	dynamic var interiorProtectionSensorStatus: DBVehicleStatusIntModel?
    dynamic var keyActivationState: DBVehicleStatusBoolModel?
	dynamic var languageHU: DBVehicleStatusIntModel?
    dynamic var lastParkEvent: DBVehicleStatusIntModel?
    dynamic var lastParkEventNotConfirmed: DBVehicleStatusBoolModel?
    dynamic var lastTheftWarning: DBVehicleStatusIntModel?
    dynamic var lastTheftWarningReason: DBVehicleStatusIntModel?
	dynamic var liquidConsumptionReset: DBVehicleStatusDoubleModel?
	dynamic var liquidConsumptionStart: DBVehicleStatusDoubleModel?
	dynamic var liquidRangeSkipIndication: DBVehicleStatusBoolModel?
	dynamic var maxRange: DBVehicleStatusIntModel?
	dynamic var maxSoc: DBVehicleStatusIntModel?
	dynamic var maxSocLowerLimit: DBVehicleStatusIntModel?
	dynamic var maxSocUpperLimit: DBVehicleStatusIntModel?
	dynamic var minSoc: DBVehicleStatusIntModel?
	dynamic var minSocLowerLimit: DBVehicleStatusIntModel?
	dynamic var minSocUpperLimit: DBVehicleStatusIntModel?
	dynamic var nextDepartureTime: DBVehicleStatusIntModel?
	dynamic var nextDepartureTimeWeekday: DBVehicleStatusIntModel?
	dynamic var odo: DBVehicleStatusIntModel?
	dynamic var parkBrakeStatus: DBVehicleStatusBoolModel?
	dynamic var parkEventLevel: DBVehicleStatusIntModel?
	dynamic var parkEventSensorStatus: DBVehicleStatusIntModel?
	dynamic var parkEventType: DBVehicleStatusIntModel?
	dynamic var positionErrorCode: DBVehicleStatusIntModel?
	dynamic var positionHeading: DBVehicleStatusDoubleModel?
	dynamic var positionLat: DBVehicleStatusDoubleModel?
	dynamic var positionLong: DBVehicleStatusDoubleModel?
	dynamic var precondActive: DBVehicleStatusBoolModel?
	dynamic var precondAtDeparture: DBVehicleStatusBoolModel?
	dynamic var precondAtDepartureDisable: DBVehicleStatusBoolModel?
	dynamic var precondDuration: DBVehicleStatusIntModel?
	dynamic var precondError: DBVehicleStatusIntModel?
	dynamic var precondNow: DBVehicleStatusBoolModel?
	dynamic var precondNowError: DBVehicleStatusIntModel?
	dynamic var precondSeatFrontLeft: DBVehicleStatusBoolModel?
	dynamic var precondSeatFrontRight: DBVehicleStatusBoolModel?
	dynamic var precondSeatRearLeft: DBVehicleStatusBoolModel?
	dynamic var precondSeatRearRight: DBVehicleStatusBoolModel?
    dynamic var proximityCalculationForVehiclePositionRequired: DBVehicleStatusBoolModel?
	dynamic var remoteStartActive: DBVehicleStatusBoolModel?
	dynamic var remoteStartEndtime: DBVehicleStatusIntModel?
	dynamic var remoteStartTemperature: DBVehicleStatusDoubleModel?
	dynamic var roofTopStatus: DBVehicleStatusIntModel?
	dynamic var selectedChargeProgram: DBVehicleStatusIntModel?
	dynamic var serviceIntervalDays: DBVehicleStatusIntModel?
	dynamic var serviceIntervalDistance: DBVehicleStatusIntModel?
	dynamic var smartCharging: DBVehicleStatusIntModel?
	dynamic var smartChargingAtDeparture: DBVehicleStatusBoolModel?
	dynamic var smartChargingAtDeparture2: DBVehicleStatusBoolModel?
	dynamic var soc: DBVehicleStatusIntModel?
	dynamic var socProfile: DBVehicleStatusSocProfileModel?
    dynamic var speedAlert: DBVehicleStatusSpeedAlertModel?
	dynamic var speedUnitFromIC: DBVehicleStatusBoolModel?
	dynamic var starterBatteryState: DBVehicleStatusIntModel?
	dynamic var sunroofBlindFrontStatus: DBVehicleStatusIntModel?
	dynamic var sunroofBlindRearStatus: DBVehicleStatusIntModel?
	dynamic var sunroofEventState: DBVehicleStatusIntModel?
	dynamic var sunroofEventActive: DBVehicleStatusBoolModel?
	dynamic var sunroofState: DBVehicleStatusIntModel?
	dynamic var tankAdBlueLevel: DBVehicleStatusIntModel?
	dynamic var tankElectricRange: DBVehicleStatusIntModel?
	dynamic var tankGasLevel: DBVehicleStatusDoubleModel?
	dynamic var tankGasRange: DBVehicleStatusDoubleModel?
	dynamic var tankLiquidLevel: DBVehicleStatusIntModel?
	dynamic var tankLiquidRange: DBVehicleStatusIntModel?
	dynamic var tankOverallRange: DBVehicleStatusDoubleModel?
    dynamic var teenageDrivingMode: DBVehicleStatusIntModel?
	dynamic var temperaturePointFrontCenter: DBVehicleStatusDoubleModel?
	dynamic var temperaturePointFrontLeft: DBVehicleStatusDoubleModel?
	dynamic var temperaturePointFrontRight: DBVehicleStatusDoubleModel?
	dynamic var temperaturePointRearCenter: DBVehicleStatusDoubleModel?
	dynamic var temperaturePointRearCenter2: DBVehicleStatusDoubleModel?
	dynamic var temperaturePointRearLeft: DBVehicleStatusDoubleModel?
	dynamic var temperaturePointRearRight: DBVehicleStatusDoubleModel?
	dynamic var temperatureUnitHU: DBVehicleStatusBoolModel?
	dynamic var theftSystemArmed: DBVehicleStatusBoolModel?
	dynamic var theftAlarmActive: DBVehicleStatusBoolModel?
	dynamic var timeFormatHU: DBVehicleStatusBoolModel?
	dynamic var tireMarkerFrontLeft: DBVehicleStatusIntModel?
	dynamic var tireMarkerFrontRight: DBVehicleStatusIntModel?
	dynamic var tireMarkerRearLeft: DBVehicleStatusIntModel?
	dynamic var tireMarkerRearRight: DBVehicleStatusIntModel?
	dynamic var tirePressureFrontLeft: DBVehicleStatusDoubleModel?
	dynamic var tirePressureFrontRight: DBVehicleStatusDoubleModel?
	dynamic var tirePressureMeasTimestamp: DBVehicleStatusIntModel?
	dynamic var tirePressureRearLeft: DBVehicleStatusDoubleModel?
	dynamic var tirePressureRearRight: DBVehicleStatusDoubleModel?
	dynamic var tireSensorAvailable: DBVehicleStatusIntModel?
	dynamic var towProtectionSensorStatus: DBVehicleStatusIntModel?
	dynamic var trackingStateHU: DBVehicleStatusBoolModel?
    dynamic var valetDrivingMode: DBVehicleStatusIntModel?
	dynamic var vehicleDataConnectionState: DBVehicleStatusDoubleModel?
	dynamic var vehicleLockState: DBVehicleStatusIntModel?
	dynamic var vTime: DBVehicleStatusIntModel?
	dynamic var warningBrakeFluid: DBVehicleStatusBoolModel?
	dynamic var warningBrakeLiningWear: DBVehicleStatusBoolModel?
	dynamic var warningCoolantLevelLow: DBVehicleStatusBoolModel?
	dynamic var warningEngineLight: DBVehicleStatusBoolModel?
	dynamic var warningTireLamp: DBVehicleStatusIntModel?
	dynamic var warningTireLevelPrw: DBVehicleStatusIntModel?
	dynamic var warningTireSprw: DBVehicleStatusBoolModel?
	dynamic var warningTireSrdk: DBVehicleStatusIntModel?
	dynamic var warningWashWater: DBVehicleStatusBoolModel?
	dynamic var weekdaytariff: DBVehicleStatusTariffModel?
	dynamic var weekendtariff: DBVehicleStatusTariffModel?
	dynamic var weeklyProfile: DBVehicleStatusWeeklyProfileModel?
	dynamic var weeklySetHU: DBVehicleStatusDayTimeModel?
	dynamic var windowBlindRearStatus: DBVehicleStatusIntModel?
	dynamic var windowBlindRearLeftStatus: DBVehicleStatusIntModel?
	dynamic var windowBlindRearRightStatus: DBVehicleStatusIntModel?
	dynamic var windowFrontLeftState: DBVehicleStatusIntModel?
	dynamic var windowFrontRightState: DBVehicleStatusIntModel?
	dynamic var windowRearLeftState: DBVehicleStatusIntModel?
	dynamic var windowRearRightState: DBVehicleStatusIntModel?
	dynamic var windowStatusOverall: DBVehicleStatusIntModel?
	dynamic var zevActive: DBVehicleStatusBoolModel?
	
	// MARK: - Realm
	
	override static func primaryKey() -> String? {
		return "finOrVin"
	}
}
